name: Generate Private Repo Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate_stats:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: npm ci
    - name: Generate stats
      run: node generate-stats.js
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Commit and push changes
      run: |
        git config user.name "GitHub Action"
        git config user.email "noreply@github.com"
        git add .
        git commit -m "Update private repo stats"
        git push
